/-Datatypes that allow choices are called sum types and datatypes that can
include instances of themselves are called recursive datatypes. Recursive sum
types are called inductive datatypes, because mathematical induction may be
used to prove statements about them.-/

/-Bool is an inductive datatype:

inductive Bool where
  | false : Bool
  | true : Bool

The first line provides the name of the new type (Bool), while the remaining
lines each describe a constructor.

OOP analogue:
abstract class Bool {}
class True : Bool {}
class False : Bool {}

Though in Lean, true and false are not subtypes; the only type is Bool

Nat is also inductive:
inductive Nat where
  | zero : Nat
  | succ (n : Nat) : Nat
Notice that many familiar properties of the natural numbers come about for free
here from Lean semantics. For example:
*Product types act like disjoint unions, so a priori the two cases here are
 disjoint. This means zero is automatically not itself a successor. Lean calls
 this `constructor disjointness.'
*The cases here are similarly exhaustive, so we don't have some other zeroprime
 element floating around sourcing its own parallel natural number line. Lean
 calls this `exhaustiveness.'
*The succesor function is not actually defined here, so it behaves like a free
 group generated by some symbol set modulo an empty set of relations, wherein
 (for lack of any relations by which to quotient) any two typographically
 distinct strings are distinct as elements. Similarly succ(n) = succ(m) iff
 n = m. More locally, this comes from Lean's `constructor injectivity.'
The first property then implies 0 != succ(...(succ(0))). Repeated application
of the third then gives n != succ(...(succ(n))) for general n arising as a
(generally iterated) successor of 0.

But these three properties alone don't forbid the existence of elements not of
the form succ(...(succ(0)))! They allow the disjoint union of 0 with arbitrary
copies of ℤ or additive quotients thereof. What forbids is an addition semantic
property of an inductive declaration, namely the `induction principle.' This is
the familiar law
  (P(zero) and (P(n) → P(succ(n))) → P(n) ∀n
More concretely, a priori every object having whatever inductive type we have
just defined is obtained by finitely many applications of only the given
constructors.
Equivalently, Nat is specifically the freely generated / initial inductive
object generated by zero and succ.
-/
